"use client";
import { useEffect, useState } from "react";
import { useAuth } from "../../src/features/auth/AuthProvider";
import { apiRequest } from "../../src/lib/api";
type Snapshot = { portfolio: { starts: number; completes: number; qualityTerminates: number; abandons: number; conversionRate: number }; suppliers: Array<{ name: string; starts: number; completes: number; incidenceRate: number; cost: number }>; clients: Array<{ name: string; completes: number }>; markets: Array<{ countryCode: string; completes: number }> };
const empty: Snapshot = { portfolio: { starts: 0, completes: 0, qualityTerminates: 0, abandons: 0, conversionRate: 0 }, suppliers: [], clients: [], markets: [] };
function csv(value: unknown) { let text = String(value ?? ""); if (/^[=+\-@]/.test(text)) text = `'${text}`; return `"${text.replaceAll('"', '""')}"`; }
export function AnalyticsDashboard() {
  const { configured, session } = useAuth(); const [data, setData] = useState(empty); const [error, setError] = useState(""); const [to, setTo] = useState(() => new Date().toISOString().slice(0, 10)); const [from, setFrom] = useState(() => new Date(Date.now() - 30 * 86400000).toISOString().slice(0, 10)); const token = session?.access_token;
  useEffect(() => { if (configured && !token) return; void apiRequest<{ data: Snapshot }>(`/api/analytics?from=${from}&to=${to}`, { headers: token ? { authorization: `Bearer ${token}` } : undefined }).then((response) => { setData(response.data); setError(""); }).catch(() => setError("Analytics could not be loaded.")); }, [configured, from, to, token]);
  function exportCsv() { const rows: unknown[][] = [["Section", "Source", "Starts", "Completes", "Incidence rate", "Conversion rate", "Cost"], ["Portfolio", "Organization", data.portfolio.starts, data.portfolio.completes, "", data.portfolio.conversionRate, ""], ...data.suppliers.map((item) => ["Supplier", item.name, item.starts, item.completes, item.incidenceRate, item.starts ? 100 * item.completes / item.starts : 0, item.cost]), ...data.clients.map((item) => ["Client", item.name, "", item.completes, "", "", ""]), ...data.markets.map((item) => ["Market", item.countryCode, "", item.completes, "", "", ""])]; const blob = new Blob(["\uFEFF", rows.map((row) => row.map(csv).join(",")).join("\r\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `analytics-${from}-to-${to}.csv`; anchor.click(); URL.revokeObjectURL(url); }
  const p = data.portfolio;
  return <><div className="page-head"><div><div className="eyebrow">Portfolio intelligence</div><h1 className="page-title">Analytics</h1><p className="page-subtitle">Compare supplier, client, and market sources to identify delivery and cost issues.</p></div><div className="head-actions"><input aria-label="Analytics start date" className="control" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /><input aria-label="Analytics end date" className="control" type="date" value={to} onChange={(event) => setTo(event.target.value)} /><button className="button" type="button" onClick={exportCsv}>Export CSV</button></div></div>{error ? <div className="form-error data-error" role="alert">{error}</div> : null}<div className="metric-strip"><Metric label="Starts" value={p.starts} /><Metric label="Completes" value={p.completes} /><Metric label="Conversion" value={`${p.conversionRate ?? 0}%`} /><Metric label="Quality / abandon" value={`${p.qualityTerminates} / ${p.abandons}`} /></div><div className="split-grid"><Rollup title="Client completes" rows={data.clients.map((item) => [item.name, item.completes])} /><Rollup title="Market completes" rows={data.markets.map((item) => [item.countryCode, item.completes])} /></div><section className="panel" style={{ marginTop: 16 }}><div className="panel-head"><div><h2 className="panel-title">Supplier efficiency</h2><span className="panel-note">Low conversion or incidence with high cost identifies weak sources.</span></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Supplier</th><th>Starts</th><th>Completes</th><th>Conversion</th><th>IR</th><th>Cost</th><th>Cost / complete</th></tr></thead><tbody>{data.suppliers.map((item) => <tr key={item.name}><td><strong>{item.name}</strong></td><td>{item.starts}</td><td>{item.completes}</td><td>{item.starts ? (100 * item.completes / item.starts).toFixed(1) : "0.0"}%</td><td>{item.incidenceRate ?? 0}%</td><td>${Number(item.cost ?? 0).toLocaleString()}</td><td>${item.completes ? (Number(item.cost ?? 0) / item.completes).toFixed(2) : "0.00"}</td></tr>)}</tbody></table></div></section></>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="panel metric-card"><div className="metric-top"><span>{label}</span></div><div className="metric-value">{typeof value === "number" ? value.toLocaleString() : value}</div></div>; }
function Rollup({ title, rows }: { title: string; rows: Array<[string, number]> }) { const max = Math.max(1, ...rows.map((row) => row[1])); return <section className="panel chart-panel"><div className="panel-head" style={{ margin: "-20px -20px 0" }}><h2 className="panel-title">{title}</h2></div><div style={{ paddingTop: 24, display: "grid", gap: 16 }}>{rows.map(([name, value]) => <div key={name}><div style={{ display: "flex", justifyContent: "space-between", fontSize: 11, marginBottom: 6 }}><strong>{name}</strong><span>{value}</span></div><div style={{ height: 8, borderRadius: 999, background: "#ebece7" }}><div style={{ width: `${100 * value / max}%`, height: "100%", borderRadius: 999, background: "var(--brand)" }} /></div></div>)}</div></section>; }
