"use client";
import { useEffect, useState } from "react";
import { useAuth } from "../../src/features/auth/AuthProvider";
import { apiRequest } from "../../src/lib/api";
type Snapshot = { portfolio: { testStarts: number; testCompletes: number; testTerminates: number; testOverQuota: number; testQualityTerminates: number; starts: number; reached: number; completes: number; terminates: number; overQuota: number; qualityTerminates: number; abandons: number; incidenceRate: number; conversionRate: number }; suppliers: Array<{ name: string; starts: number; reached: number; completes: number; terminates: number; overQuota: number; qualityTerminates: number; incidenceRate: number; conversionRate: number; cost: number }>; clients: Array<{ name: string; completes: number }>; markets: Array<{ countryCode: string; completes: number }> };
const empty: Snapshot = { portfolio: { testStarts: 0, testCompletes: 0, testTerminates: 0, testOverQuota: 0, testQualityTerminates: 0, starts: 0, reached: 0, completes: 0, terminates: 0, overQuota: 0, qualityTerminates: 0, abandons: 0, incidenceRate: 0, conversionRate: 0 }, suppliers: [], clients: [], markets: [] };
function csv(value: unknown) { let text = String(value ?? ""); if (/^[=+\-@]/.test(text)) text = `'${text}`; return `"${text.replaceAll('"', '""')}"`; }
export function AnalyticsDashboard() {
  const { configured, session } = useAuth(); const [data, setData] = useState(empty); const [error, setError] = useState(""); const [to, setTo] = useState(() => new Date().toISOString().slice(0, 10)); const [from, setFrom] = useState(() => new Date(Date.now() - 30 * 86400000).toISOString().slice(0, 10)); const token = session?.access_token;
  useEffect(() => { if (configured && !token) return; void apiRequest<{ data: Snapshot }>(`/api/analytics?from=${from}&to=${to}`, { headers: token ? { authorization: `Bearer ${token}` } : undefined }).then((response) => { setData(response.data); setError(""); }).catch(() => setError("Analytics could not be loaded.")); }, [configured, from, to, token]);
  function exportCsv() { const rows: unknown[][] = [["Section", "Source", "Starts", "Reached client", "Completes", "Terminates", "Quota full", "Quality terminates", "IR % (CO/(CO+TE))", "Conversion % (CO/RC)", "Cost"], ["Portfolio", "Organization", data.portfolio.starts, data.portfolio.reached, data.portfolio.completes, data.portfolio.terminates, data.portfolio.overQuota, data.portfolio.qualityTerminates, data.portfolio.incidenceRate, data.portfolio.conversionRate, ""], ...data.suppliers.map((item) => ["Supplier", item.name, item.starts, item.reached, item.completes, item.terminates, item.overQuota, item.qualityTerminates, item.incidenceRate, item.conversionRate, item.cost]), ["Test", "Organization", data.portfolio.testStarts, "", data.portfolio.testCompletes, data.portfolio.testTerminates, data.portfolio.testOverQuota, data.portfolio.testQualityTerminates, "", "", ""], ...data.clients.map((item) => ["Client", item.name, "", "", item.completes, "", "", "", "", "", ""]), ...data.markets.map((item) => ["Market", item.countryCode, "", "", item.completes, "", "", "", "", "", ""])]; const blob = new Blob(["\uFEFF", rows.map((row) => row.map(csv).join(",")).join("\r\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `analytics-${from}-to-${to}.csv`; anchor.click(); URL.revokeObjectURL(url); }
  const p = data.portfolio;
  return <><div className="page-head"><div><div className="eyebrow">Portfolio intelligence</div><h1 className="page-title">Analytics</h1><p className="page-subtitle">IR = CO / (CO + TE). Conversion = CO / reached-client respondents.</p></div><div className="head-actions"><input aria-label="Analytics start date" className="control" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /><input aria-label="Analytics end date" className="control" type="date" value={to} onChange={(event) => setTo(event.target.value)} /><button className="button" type="button" onClick={exportCsv}>Export CSV</button></div></div>{error ? <div className="form-error data-error" role="alert">{error}</div> : null}<div className="metric-strip"><Metric label="Starts / reached" value={`${p.starts} / ${p.reached}`} /><Metric label="Completes / terminates" value={`${p.completes} / ${p.terminates}`} /><Metric label="IR / conversion" value={`${p.incidenceRate ?? 0}% / ${p.conversionRate ?? 0}%`} /><Metric label="Quota / quality / abandon" value={`${p.overQuota} / ${p.qualityTerminates} / ${p.abandons}`} /></div><div className="split-grid"><Rollup title="Client completes" rows={data.clients.map((item) => [item.name, item.completes])} /><Rollup title="Market completes" rows={data.markets.map((item) => [item.countryCode, item.completes])} /></div><section id="supplier-efficiency" className="panel" style={{ marginTop: 16 }}><div className="panel-head"><div><h2 className="panel-title">Supplier efficiency</h2><span className="panel-note">Every terminal outcome is separate; IR and conversion use the formulas shown above.</span></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Supplier</th><th>ST</th><th>RC</th><th>CO</th><th>TE</th><th>OQ</th><th>QT</th><th>IR</th><th>Conversion</th><th>Cost</th><th>Cost / complete</th></tr></thead><tbody>{data.suppliers.map((item) => <tr key={item.name}><td><strong>{item.name}</strong></td><td>{item.starts}</td><td>{item.reached}</td><td>{item.completes}</td><td>{item.terminates}</td><td>{item.overQuota}</td><td>{item.qualityTerminates}</td><td>{item.incidenceRate ?? 0}%</td><td>{item.conversionRate ?? 0}%</td><td>${Number(item.cost ?? 0).toLocaleString()}</td><td>${item.completes ? (Number(item.cost ?? 0) / item.completes).toFixed(2) : "0.00"}</td></tr>)}</tbody></table></div></section></>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="panel metric-card"><div className="metric-top"><span>{label}</span></div><div className="metric-value">{typeof value === "number" ? value.toLocaleString() : value}</div></div>; }
function Rollup({ title, rows }: { title: string; rows: Array<[string, number]> }) { const max = Math.max(1, ...rows.map((row) => row[1])); return <section className="panel chart-panel"><div className="panel-head" style={{ margin: "-20px -20px 0" }}><h2 className="panel-title">{title}</h2></div><div style={{ paddingTop: 24, display: "grid", gap: 16 }}>{rows.map(([name, value]) => <div key={name}><div style={{ display: "flex", justifyContent: "space-between", fontSize: 11, marginBottom: 6 }}><strong>{name}</strong><span>{value}</span></div><div style={{ height: 8, borderRadius: 999, background: "#ebece7" }}><div style={{ width: `${100 * value / max}%`, height: "100%", borderRadius: 999, background: "var(--brand)" }} /></div></div>)}</div></section>; }
