"use client";
import Link from "./NavigationLink";
import { useEffect, useState } from "react";
import { useAuth } from "../../src/features/auth/AuthProvider";
import { apiRequest } from "../../src/lib/api";
type Analytics = { portfolio: { starts: number; completes: number; qualityTerminates: number; abandons: number; conversionRate: number }; suppliers: Array<{ name: string; starts: number; completes: number; incidenceRate: number; cost: number }> };
type Notice = { id: string; title: string; body: string; createdAt: string };
export function Dashboard() {
  const { configured, session } = useAuth(); const [data, setData] = useState<Analytics>({ portfolio: { starts: 0, completes: 0, qualityTerminates: 0, abandons: 0, conversionRate: 0 }, suppliers: [] }); const [live, setLive] = useState(0); const [notices, setNotices] = useState<Notice[]>([]); const [error, setError] = useState(""); const token = session?.access_token;
  useEffect(() => { if (configured && !token) return; const headers = token ? { authorization: `Bearer ${token}` } : undefined; void Promise.all([apiRequest<{ data: Analytics }>("/api/analytics", { headers }), apiRequest<{ meta: { summary: { statuses: { LIVE: number } } } }>("/api/projects?page=1&pageSize=1&scope=all", { headers }), apiRequest<{ data: Notice[] }>("/api/notifications", { headers })]).then(([analytics, projectResponse, notificationResponse]) => { setData(analytics.data); setLive(projectResponse.meta.summary.statuses.LIVE); setNotices(notificationResponse.data.slice(0, 5)); setError(""); }).catch(() => setError("Dashboard data could not be loaded.")); }, [configured, token]);
  const p = data.portfolio; const cost = data.suppliers.reduce((sum, item) => sum + Number(item.cost || 0), 0); const maxStarts = Math.max(1, ...data.suppliers.map((item) => item.starts));
  return <>{error ? <div className="form-error data-error" role="alert">{error}</div> : null}<div className="page-head"><div><div className="eyebrow">{new Date().toLocaleDateString(undefined, { weekday: "long", day: "numeric", month: "long" })}</div><h1 className="page-title">Fieldwork overview</h1><p className="page-subtitle">Organization-wide delivery, conversion, cost, and operational alerts.</p></div><div className="head-actions"><Link className="button" href="/analytics">View analytics</Link></div></div><div className="metric-strip"><Metric label="Live projects" value={live} note="Across the organization" tint="#cae7df" /><Metric label="Monthly completes" value={p.completes} note={`${p.starts.toLocaleString()} starts`} tint="#f2dfbb" /><Metric label="Conversion" value={`${Number(p.conversionRate || 0).toFixed(1)}%`} note={`${p.qualityTerminates} quality terms`} tint="#dbe3f2" /><Metric label="Supplier cost" value={`$${cost.toLocaleString(undefined, { maximumFractionDigits: 0 })}`} note="Last 30 days" tint="#f1d7ce" /></div><div className="dashboard-grid"><section className="panel chart-panel"><div className="panel-head" style={{ margin: "-20px -20px 0" }}><div><h2 className="panel-title">Supplier delivery</h2><span className="panel-note">Organization-wide starts and completes</span></div><Link className="button small ghost" href="/analytics">Open analytics →</Link></div><div className="chart-bars">{data.suppliers.slice(0, 7).map((item) => <div className="bar-group" key={item.name}><div className="bar" style={{ height: `${100 * item.starts / maxStarts}%` }} title={`${item.starts} starts`} /><div className="bar alt" style={{ height: `${100 * item.completes / maxStarts}%` }} title={`${item.completes} completes`} /><span className="bar-label">{item.name.slice(0, 4)}</span></div>)}</div></section><section className="panel"><div className="panel-head"><h2 className="panel-title">Live activity</h2><Link className="panel-note" href="/notifications">All alerts</Link></div><div className="activity-list">{notices.map((item) => <div className="activity-item" key={item.id}><span className="activity-dot" /><div><strong>{item.title}</strong><span>{item.body}</span></div><span className="activity-time">{new Date(item.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span></div>)}{notices.length === 0 ? <p className="panel-note">No recent operational alerts.</p> : null}</div></section></div></>;
}
function Metric({ label, value, note, tint }: { label: string; value: string | number; note: string; tint: string }) { return <div className="panel metric-card" style={{ "--metric-tint": tint } as React.CSSProperties}><div className="metric-top"><span>{label}</span><span className="metric-delta">{note}</span></div><div className="metric-value">{typeof value === "number" ? value.toLocaleString() : value}</div></div>; }
