"use client";
import { useEffect, useState } from "react";
import { useAuth } from "../../src/features/auth/AuthProvider";
import { apiRequest } from "../../src/lib/api";
type Notice = { id: string; eventType: string; severity: string; title: string; body: string; readAt: string | null; createdAt: string };
type Rule = { eventType: string; inAppEnabled: boolean; emailEnabled: boolean; threshold: number | null };
export function NotificationCenter() {
  const { configured, session } = useAuth(); const [notices, setNotices] = useState<Notice[]>([]); const [rules, setRules] = useState<Rule[]>([]); const [canAdminister, setCanAdminister] = useState(!configured); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const token = session?.access_token; const headers = token ? { authorization: `Bearer ${token}` } : undefined;
  useEffect(() => { if (configured && !token) return; const requestHeaders = token ? { authorization: `Bearer ${token}` } : undefined; void Promise.all([apiRequest<{ data: Notice[] }>("/api/notifications", { headers: requestHeaders }), apiRequest<{ data: Rule[]; meta: { canAdminister?: boolean } }>("/api/notification-rules", { headers: requestHeaders })]).then(([a, b]) => { setNotices(a.data); setRules(b.data); setCanAdminister(b.meta.canAdminister === true); }).catch(() => setMessage("Notifications could not be loaded.")); }, [configured, token]);
  async function markRead(item: Notice) { if (item.readAt) return; try { const response = await apiRequest<{ data: { readAt: string } }>(`/api/notifications/${item.id}`, { method: "PATCH", headers }); setNotices((current) => current.map((notice) => notice.id === item.id ? { ...notice, readAt: response.data.readAt } : notice)); } catch { setMessage("Notification could not be marked read."); } }
  async function saveRules() { setSaving(true); setMessage(""); try { const response = await apiRequest<{ data: Rule[] }>("/api/notification-rules", { method: "PUT", headers, body: JSON.stringify({ rules }) }); setRules(response.data); setMessage("Alert rules saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Alert rules could not be saved."); } finally { setSaving(false); } }
  function updateRule(index: number, change: Partial<Rule>) { setRules((current) => current.map((rule, position) => position === index ? { ...rule, ...change } : rule)); }
  return <><div className="page-head"><div><div className="eyebrow">Operational awareness</div><h1 className="page-title">Notifications</h1><p className="page-subtitle">Project, pacing, quota, quality, and callback alerts in one place.</p></div><button className="button primary" type="button" disabled={!canAdminister || saving || rules.length === 0} onClick={() => void saveRules()}>{saving ? "Saving…" : "Save alert rules"}</button></div>{message ? <div className="form-error data-error" role="status">{message}</div> : null}<div className="split-grid"><section className="panel"><div className="panel-head"><h2 className="panel-title">Inbox</h2><span className="panel-note">{notices.filter((notice) => !notice.readAt).length} unread</span></div><div className="info-list">{notices.map((item) => <button key={item.id} type="button" className="info-row" style={{ width: "100%", border: 0, background: item.readAt ? "transparent" : "#fff8f5", textAlign: "left" }} onClick={() => void markRead(item)}><span>{new Date(item.createdAt).toLocaleString()} · {item.severity}</span><strong>{item.title}</strong></button>)}</div></section><section className="panel"><div className="panel-head"><div><h2 className="panel-title">Alert rules</h2><span className="panel-note">{canAdminister ? "Email delivery activates after a provider is configured." : "Administrator access is required to change rules."}</span></div></div><div className="info-list">{rules.map((rule, index) => <div className="info-row" key={rule.eventType}><span>{rule.eventType.replaceAll("_", " ")}</span><div className="row-actions">{rule.eventType === "PACING_RISK" ? <label>Pacing threshold <input aria-label="Pacing risk threshold percent" className="control" style={{ width: 76 }} type="number" min="1" max="100" value={rule.threshold ?? 80} disabled={!canAdminister} onChange={(event) => updateRule(index, { threshold: Number(event.target.value) })} />%</label> : null}<label><input type="checkbox" checked={rule.inAppEnabled} disabled={!canAdminister} onChange={(event) => updateRule(index, { inAppEnabled: event.target.checked })} /> In-app</label><label><input type="checkbox" checked={rule.emailEnabled} disabled={!canAdminister} onChange={(event) => updateRule(index, { emailEnabled: event.target.checked })} /> Email</label></div></div>)}</div></section></div></>;
}
