"use client";
import { useEffect, useState } from "react";
import { apiRequest } from "../../src/lib/api";
type Market = { id?: string; countryCode: string; languageCode: string; targetQuota: number; expectedLoiMinutes: number; expectedIr: number };
const blankMarket = (): Market => ({ countryCode: "US", languageCode: "en", targetQuota: 100, expectedLoiMinutes: 10, expectedIr: 40 });
export function ProjectMarketsEditor({ projectId, configured, token, canOperate }: { projectId: string; configured: boolean; token?: string; canOperate: boolean }) {
  const [markets, setMarkets] = useState<Market[]>([]); const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { if (configured && !token) return; const headers = token ? { authorization: `Bearer ${token}` } : undefined; void apiRequest<{ data: Market[] }>(`/api/projects/${encodeURIComponent(projectId)}/markets`, { headers }).then((response) => setMarkets(response.data)).catch(() => setMessage("Market configuration could not be loaded.")); }, [configured, projectId, token]);
  function change(index: number, field: keyof Market, value: string) { setMarkets((current) => current.map((market, position) => position === index ? { ...market, [field]: ["targetQuota", "expectedLoiMinutes", "expectedIr"].includes(field) ? Number(value) : value } : market)); }
  async function save() { setBusy(true); setMessage(""); try { const response = await apiRequest<{ data: Market[] }>(`/api/projects/${encodeURIComponent(projectId)}/markets`, { method: "PUT", headers: token ? { authorization: `Bearer ${token}` } : undefined, body: JSON.stringify({ markets }) }); setMarkets(response.data); setEditing(false); setMessage("Markets and quotas saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Markets could not be saved."); } finally { setBusy(false); } }
  const totalQuota = markets.reduce((total, market) => total + (Number.isFinite(market.targetQuota) ? market.targetQuota : 0), 0);
  return <section className="panel" style={{ marginTop: 16 }}><div className="panel-head"><div><h2 className="panel-title">Markets and quotas</h2><span className="panel-note">{markets.length} markets · {totalQuota.toLocaleString()} target completes</span></div>{canOperate ? <button className="button small ghost" type="button" onClick={() => setEditing((value) => !value)}>{editing ? "Cancel" : "Edit markets"}</button> : null}</div>{message ? <div className="form-error data-error" role="status">{message}</div> : null}<div className="table-wrap"><table className="data-table" style={{ minWidth: 760 }}><thead><tr><th>Country</th><th>Language</th><th>Target quota</th><th>Expected LOI</th><th>Expected IR</th>{editing ? <th>Action</th> : null}</tr></thead><tbody>{markets.map((market, index) => <tr key={`${index}-${market.id ?? "new"}`}><MarketCell editing={editing} value={market.countryCode} label="Country code" onChange={(value) => change(index, "countryCode", value.toUpperCase())} maxLength={2} /><MarketCell editing={editing} value={market.languageCode} label="Language code" onChange={(value) => change(index, "languageCode", value.toLowerCase())} maxLength={20} /><MarketCell editing={editing} value={market.targetQuota} label="Target quota" onChange={(value) => change(index, "targetQuota", value)} type="number" /><MarketCell editing={editing} value={market.expectedLoiMinutes} label="Expected LOI" onChange={(value) => change(index, "expectedLoiMinutes", value)} type="number" /><MarketCell editing={editing} value={market.expectedIr} label="Expected IR" onChange={(value) => change(index, "expectedIr", value)} type="number" />{editing ? <td><button className="button small ghost" disabled={markets.length === 1} type="button" onClick={() => setMarkets((current) => current.filter((_, position) => position !== index))}>Remove</button></td> : null}</tr>)}</tbody></table></div>{editing ? <div className="table-footer"><button className="button small" type="button" onClick={() => setMarkets((current) => [...current, blankMarket()])}>＋ Add market</button><button className="button primary small" disabled={busy || markets.length === 0} type="button" onClick={() => void save()}>{busy ? "Saving…" : "Save markets"}</button></div> : null}</section>;
}
function MarketCell({ editing, value, label, onChange, type = "text", maxLength }: { editing: boolean; value: string | number; label: string; onChange: (value: string) => void; type?: string; maxLength?: number }) { return <td>{editing ? <input aria-label={label} className="control" type={type} min={type === "number" ? (label === "Expected IR" ? 0 : 1) : undefined} max={label === "Expected IR" ? 100 : undefined} step={label === "Expected IR" ? "0.1" : "1"} maxLength={maxLength} value={value} onChange={(event) => onChange(event.target.value)} required /> : label === "Expected LOI" ? `${value} min` : label === "Expected IR" ? `${value}%` : value}</td>; }
