"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { apiRequest } from "../../src/lib/api";

type Parameter = { name: string; value: string };
type Setup = { liveUrl: string; testUrl: string; parameters: Parameter[] };
const emptySetup: Setup = { liveUrl: "", testUrl: "", parameters: [{ name: "PID", value: "{{project_id}}" }, { name: "RID", value: "{{respondent_id}}" }] };

export function ProjectSurveySetupEditor({ projectId, configured, token, canOperate }: { projectId: string; configured: boolean; token?: string; canOperate: boolean }) {
  const [setup, setSetup] = useState<Setup>(emptySetup); const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const headers = useMemo(() => token ? { authorization: `Bearer ${token}` } : undefined, [token]);
  const load = useCallback(async () => { if (configured && !token) return; try { const response = await apiRequest<{ data: Setup }>(`/api/projects/${encodeURIComponent(projectId)}/survey-setup`, { headers }); setSetup(response.data); setMessage(""); } catch { setMessage("Survey routing setup could not be loaded."); } }, [configured, headers, projectId, token]);
  useEffect(() => { const initial = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(initial); }, [load]);
  function updateParameter(index: number, field: keyof Parameter, value: string) { setSetup((current) => ({ ...current, parameters: current.parameters.map((item, position) => position === index ? { ...item, [field]: value } : item) })); }
  async function save() { setBusy(true); setMessage(""); try { const response = await apiRequest<{ data: Setup }>(`/api/projects/${encodeURIComponent(projectId)}/survey-setup`, { method: "PUT", headers, body: JSON.stringify(setup) }); setSetup(response.data); setEditing(false); setMessage("Survey routing saved. Test and live links now deploy these parameters automatically."); } catch (error) { setMessage(error instanceof Error ? error.message : "Survey routing setup could not be saved."); } finally { setBusy(false); } }
  return <section className="panel" style={{ marginTop: 16 }}><div className="panel-head"><div><h2 className="panel-title">Survey routing setup</h2><span className="panel-note">Separate test/live destinations with automatic project, respondent, session, callback, and eligibility parameters.</span></div>{canOperate ? <button className="button small ghost" type="button" onClick={() => editing ? void load().then(() => setEditing(false)) : setEditing(true)}>{editing ? "Cancel" : "Edit survey routing"}</button> : null}</div>{message ? <div className="form-error data-error" role="status">{message}</div> : null}
    {editing ? <><div className="form-grid"><div className="field full"><label htmlFor="routing-live-url">Live survey URL</label><input className="control" id="routing-live-url" type="url" value={setup.liveUrl} onChange={(event) => setSetup((current) => ({ ...current, liveUrl: event.target.value }))} /></div><div className="field full"><label htmlFor="routing-test-url">Test survey URL</label><input className="control" id="routing-test-url" type="url" value={setup.testUrl} onChange={(event) => setSetup((current) => ({ ...current, testUrl: event.target.value }))} /></div></div><div className="section-head parameter-head"><div><h3>Automatic URL parameters</h3><p>Values accept system placeholders and incoming eligibility keys.</p></div><button className="button small ghost" type="button" onClick={() => setSetup((current) => ({ ...current, parameters: [...current.parameters, { name: "", value: "" }] }))}>Add parameter</button></div><div className="parameter-list">{setup.parameters.map((parameter, index) => <div className="parameter-row" key={index}><div className="field"><label htmlFor={`routing-param-name-${index}`}>Parameter</label><input className="control" id={`routing-param-name-${index}`} aria-label={`Routing parameter name ${index + 1}`} value={parameter.name} onChange={(event) => updateParameter(index, "name", event.target.value)} /></div><div className="field"><label htmlFor={`routing-param-value-${index}`}>Value template</label><input className="control" id={`routing-param-value-${index}`} aria-label={`Routing parameter value ${index + 1}`} value={parameter.value} onChange={(event) => updateParameter(index, "value", event.target.value)} /></div><button className="button small ghost parameter-remove" type="button" disabled={setup.parameters.length === 1} onClick={() => setSetup((current) => ({ ...current, parameters: current.parameters.filter((_, position) => position !== index) }))}>Remove</button></div>)}</div><div className="table-footer"><span>Test URL falls back to Live when blank.</span><button className="button primary small" disabled={busy} type="button" onClick={() => void save()}>{busy ? "Saving…" : "Save routing"}</button></div></> : <div className="info-list"><Info label="Live survey" value={setup.liveUrl || "Not configured"} /><Info label="Test survey" value={setup.testUrl || (setup.liveUrl ? "Uses live survey fallback" : "Not configured")} /><Info label="Automatic parameters" value={setup.parameters.map((parameter) => `${parameter.name}=${parameter.value}`).join(" · ") || "None"} /></div>}
  </section>;
}

function Info({ label, value }: { label: string; value: string }) { return <div className="info-row"><span>{label}</span><strong>{value}</strong></div>; }
