"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { apiRequest } from "../../src/lib/api";

type Classification = "STANDARD" | "DEMOGRAPHIC" | "SENSITIVE";
type Variable = { id?: string; variableKey: string; label: string; dataClassification: Classification; retentionDays: number; active: boolean };

export function ProjectResponseVariablesEditor({ projectId, configured, token, canOperate }: { projectId: string; configured: boolean; token?: string; canOperate: boolean }) {
  const [variables, setVariables] = useState<Variable[]>([]); const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const headers = useMemo(() => token ? { authorization: `Bearer ${token}` } : undefined, [token]);
  const load = useCallback(async () => { if (configured && !token) return; try { const response = await apiRequest<{ data: Variable[] }>(`/api/projects/${encodeURIComponent(projectId)}/response-variables`, { headers }); setVariables(response.data); setMessage(""); } catch { setMessage("Response-variable configuration could not be loaded."); } }, [configured, headers, projectId, token]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  function update(index: number, changes: Partial<Variable>) { setVariables((current) => current.map((item, position) => position === index ? { ...item, ...changes } : item)); }
  async function save() { setBusy(true); setMessage(""); try { const response = await apiRequest<{ data: Variable[] }>(`/api/projects/${encodeURIComponent(projectId)}/response-variables`, { method: "PUT", headers, body: JSON.stringify({ variables }) }); setVariables(response.data); setEditing(false); setMessage("Response-variable allowlist saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Response-variable configuration could not be saved."); } finally { setBusy(false); } }
  return <section className="panel" style={{ marginTop: 16 }}><div className="panel-head"><div><h2 className="panel-title">Captured response variables</h2><span className="panel-note">Only allowlisted routing values are retained. Sensitive values have an explicit classification and retention period.</span></div>{canOperate ? <button className="button small ghost" type="button" onClick={() => editing ? void load().then(() => setEditing(false)) : setEditing(true)}>{editing ? "Cancel" : "Configure variables"}</button> : null}</div>{message ? <div className="form-error data-error" role="status">{message}</div> : null}
    {editing ? <><div className="parameter-list">{variables.map((variable, index) => <div className="parameter-row" key={variable.id ?? index}><div className="field"><label htmlFor={`capture-key-${index}`}>Variable key</label><input id={`capture-key-${index}`} className="control" value={variable.variableKey} onChange={(event) => update(index, { variableKey: event.target.value.toLowerCase() })} /></div><div className="field"><label htmlFor={`capture-label-${index}`}>Label</label><input id={`capture-label-${index}`} className="control" value={variable.label} onChange={(event) => update(index, { label: event.target.value })} /></div><div className="field"><label htmlFor={`capture-class-${index}`}>Classification</label><select id={`capture-class-${index}`} className="control" value={variable.dataClassification} onChange={(event) => update(index, { dataClassification: event.target.value as Classification })}><option>STANDARD</option><option>DEMOGRAPHIC</option><option>SENSITIVE</option></select></div><div className="field"><label htmlFor={`capture-retention-${index}`}>Retention days</label><input id={`capture-retention-${index}`} className="control" type="number" min="1" max="3650" value={variable.retentionDays} onChange={(event) => update(index, { retentionDays: Number(event.target.value) })} /></div><label className="checkbox-field"><input type="checkbox" checked={variable.active} onChange={(event) => update(index, { active: event.target.checked })} /> Active</label><button className="button small ghost parameter-remove" type="button" onClick={() => setVariables((current) => current.filter((_, position) => position !== index))}>Remove</button></div>)}</div><div className="table-footer"><button className="button small ghost" type="button" disabled={variables.length >= 30} onClick={() => setVariables((current) => [...current, { variableKey: "", label: "", dataClassification: "STANDARD", retentionDays: 365, active: true }])}>Add variable</button><button className="button primary small" type="button" disabled={busy} onClick={() => void save()}>{busy ? "Saving…" : "Save allowlist"}</button></div></> : variables.length ? <div className="info-list">{variables.map((variable) => <div className="info-row" key={variable.variableKey}><span>{variable.label} · {variable.variableKey}</span><strong>{variable.active ? "Active" : "Inactive"} · {variable.dataClassification} · {variable.retentionDays} days</strong></div>)}</div> : <p className="panel-note">No response values are retained until an operator creates an allowlist.</p>}
  </section>;
}
