"use client";
import { useEffect, useMemo, useState } from "react";
import { apiRequest } from "../../src/lib/api";

type Supplier = { id: string; name: string; status: "ACTIVE" | "INACTIVE" };
type Assignment = { id?: string; supplierId: string; supplierName?: string; supplierProjectId: string; supplierCpi: number; targetQuota: number; status: "PENDING" | "ACTIVE" | "PAUSED" | "CLOSED"; redirectMode?: string; testLink?: string; liveLink?: string; shortLink?: string; testStarts?: number; testCompletes?: number; testTerminates?: number; testOverQuota?: number; testQualityTerm?: number; starts?: number; reached?: number; completes?: number; terminates?: number; overQuota?: number; qualityTerm?: number; incidenceRate?: number; conversionRate?: number; cost?: number };

export function ProjectSuppliersEditor({ projectId, configured, token, canOperate, refreshKey }: { projectId: string; configured: boolean; token?: string; canOperate: boolean; refreshKey?: number }) {
  const [assignments, setAssignments] = useState<Assignment[]>([]); const [suppliers, setSuppliers] = useState<Supplier[]>([]); const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [linkAssignment, setLinkAssignment] = useState<Assignment | null>(null); const [copied, setCopied] = useState<"test" | "live" | "short" | "">("");
  const headers = useMemo(() => token ? { authorization: `Bearer ${token}` } : undefined, [token]);
  useEffect(() => { if (configured && !token) return; void Promise.all([apiRequest<{ data: Assignment[] }>(`/api/projects/${encodeURIComponent(projectId)}/suppliers`, { headers }), apiRequest<{ data: Supplier[] }>("/api/suppliers?status=ACTIVE", { headers })]).then(([assigned, directory]) => { setAssignments(assigned.data); setSuppliers(directory.data.filter((item) => item.status === "ACTIVE")); }).catch(() => setMessage("Supplier assignments could not be loaded.")); }, [configured, headers, projectId, refreshKey, token]);
  useEffect(() => { if (!linkAssignment) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") setLinkAssignment(null); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [linkAssignment]);
  const available = useMemo(() => suppliers.filter((supplier) => !assignments.some((item) => item.supplierId === supplier.id)), [assignments, suppliers]);
  function update(index: number, field: keyof Assignment, value: string) { setAssignments((current) => current.map((item, position) => position === index ? { ...item, [field]: ["supplierCpi", "targetQuota"].includes(field) ? Number(value) : value } : item)); }
  function add(supplierId: string) { const supplier = suppliers.find((item) => item.id === supplierId); if (supplier) setAssignments((current) => [...current, { supplierId: supplier.id, supplierName: supplier.name, supplierProjectId: "", supplierCpi: 0, targetQuota: 100, status: "PENDING" }]); }
  async function save() { setBusy(true); setMessage(""); try { await apiRequest(`/api/projects/${encodeURIComponent(projectId)}/suppliers`, { method: "PUT", headers, body: JSON.stringify({ assignments }) }); const refreshed = await apiRequest<{ data: Assignment[] }>(`/api/projects/${encodeURIComponent(projectId)}/suppliers`, { headers }); setAssignments(refreshed.data); setEditing(false); setMessage("Supplier assignments saved. Traffic states and quotas apply immediately."); } catch (error) { setMessage(error instanceof Error ? error.message : "Supplier assignments could not be saved."); } finally { setBusy(false); } }
  function testUrl(link: string) { const respondent = `ROP-TEST-${crypto.randomUUID()}`; return { respondent, url: link.replace("{{respondent_id}}", encodeURIComponent(respondent)) }; }
  async function copyTest(link: string) { const generated = testUrl(link); await navigator.clipboard.writeText(generated.url); setCopied("test"); setMessage(`Test link copied with respondent ${generated.respondent}. TST stays separate from live metrics.`); window.setTimeout(() => setCopied(""), 1800); }
  async function openTest(link: string) { const generated = testUrl(link); window.open(generated.url, "_blank", "noopener,noreferrer"); setMessage(`Test respondent ${generated.respondent} started. Refresh after the handoff to see TST.`); }
  async function copyLiveTemplate(link: string) { await navigator.clipboard.writeText(link); setCopied("live"); setMessage("Live supplier template copied. The supplier must replace {{respondent_id}} for every respondent."); window.setTimeout(() => setCopied(""), 1800); }
  async function copyShortLink(link: string) { await navigator.clipboard.writeText(link); setCopied("short"); setMessage("Clean short link copied (Cint/Toluna style). Same routing engine, same {{respondent_id}} placeholder."); window.setTimeout(() => setCopied(""), 1800); }

  return <section className="panel">
    <div className="panel-head"><div><h2 className="panel-title">Supplier delivery</h2><span className="panel-note">Test hits are separated from live delivery and cost.</span></div>{canOperate ? <button className="button small ghost" type="button" onClick={() => setEditing((value) => !value)}>{editing ? "Cancel" : "Manage suppliers"}</button> : null}</div>
    {message ? <div className="form-error data-error" role="status">{message}</div> : null}
    <div className="table-wrap"><table className="data-table" style={{ minWidth: 1600 }}><thead><tr><th>Supplier</th><th>Supplier project ID</th><th>CPI</th><th>Target</th><th title="Test starts">TST</th><th title="Test completes">TCO</th><th title="Test terminates">TTE</th><th title="Test quota full">TOQ</th><th title="Test quality terminate">TQT</th><th>ST</th><th>RC</th><th>CO</th><th>TE</th><th>OQ</th><th>QT</th><th title="CO / (CO + TE)">IR</th><th title="CO / RC">CVR</th><th>Cost</th><th>Routing</th><th>Status</th>{editing ? <th>Action</th> : null}</tr></thead><tbody>
      {assignments.map((item, index) => <tr key={item.id ?? item.supplierId}><td><strong>{item.supplierName ?? suppliers.find((supplier) => supplier.id === item.supplierId)?.name ?? "Supplier"}</strong><span className="panel-note">{item.redirectMode ?? "STATIC"}</span></td><Cell editing={editing} label="Supplier project ID" value={item.supplierProjectId} onChange={(value) => update(index, "supplierProjectId", value)} /><Cell editing={editing} label="Supplier CPI" value={item.supplierCpi} type="number" onChange={(value) => update(index, "supplierCpi", value)} /><Cell editing={editing} label="Supplier target quota" value={item.targetQuota} type="number" onChange={(value) => update(index, "targetQuota", value)} /><td>{item.testStarts ?? 0}</td><td>{item.testCompletes ?? 0}</td><td>{item.testTerminates ?? 0}</td><td>{item.testOverQuota ?? 0}</td><td>{item.testQualityTerm ?? 0}</td><td>{item.starts ?? 0}</td><td>{item.reached ?? 0}</td><td>{item.completes ?? 0}</td><td>{item.terminates ?? 0}</td><td>{item.overQuota ?? 0}</td><td>{item.qualityTerm ?? 0}</td><td>{(item.incidenceRate ?? 0).toFixed(1)}%</td><td>{(item.conversionRate ?? 0).toFixed(1)}%</td><td>${(item.cost ?? 0).toFixed(2)}</td><td>{item.testLink || item.liveLink ? <button className="button small ghost" type="button" onClick={() => { setLinkAssignment(item); setCopied(""); }}>Links</button> : <span className="panel-note">Unavailable</span>}</td><td>{editing ? <select aria-label="Assignment status" className="control" value={item.status} onChange={(event) => update(index, "status", event.target.value)}><option>PENDING</option><option>ACTIVE</option><option>PAUSED</option><option>CLOSED</option></select> : <span className={`status-pill status-${item.status}`}>{item.status}</span>}</td>{editing ? <td><button className="button small ghost" type="button" onClick={() => setAssignments((current) => current.filter((_, position) => position !== index))}>Remove</button></td> : null}</tr>)}
      {assignments.length === 0 ? <tr><td colSpan={editing ? 21 : 20} style={{ textAlign: "center", padding: 28 }}>No suppliers assigned.</td></tr> : null}
    </tbody></table></div>
    {editing ? <div className="table-footer"><select aria-label="Add supplier" className="control" style={{ width: 220 }} defaultValue="" onChange={(event) => { add(event.target.value); event.target.value = ""; }}><option value="" disabled>＋ Add supplier</option>{available.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select><button className="button primary small" disabled={busy} type="button" onClick={() => void save()}>{busy ? "Saving…" : "Save assignments"}</button></div> : null}
    {linkAssignment ? <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setLinkAssignment(null); }}><section aria-modal="true" className="panel links-modal supplier-links-modal" role="dialog" aria-labelledby="supplier-links-title"><div className="section-head"><div><div className="eyebrow">Supplier routing</div><h2 id="supplier-links-title">{linkAssignment.supplierName ?? "Supplier"} links</h2><p>Test and production links are separate. Copy the exact link needed for each flow.</p></div><button className="button small ghost" type="button" onClick={() => setLinkAssignment(null)}>Close</button></div><div className="supplier-links-grid"><article className="supplier-link-card test"><div><span className="status-pill status-PENDING">Test</span><h3>Test respondent link</h3><p>Creates a unique test respondent. It increments TST only and does not affect live cost, conversion, or quota.</p></div><code>{linkAssignment.testLink ?? "Test link unavailable"}</code><div className="modal-actions"><button className="button small ghost" disabled={!linkAssignment.testLink} type="button" onClick={() => void copyTest(linkAssignment.testLink!)}>{copied === "test" ? "Copied" : "Copy test"}</button><button className="button small primary" disabled={!linkAssignment.testLink} type="button" onClick={() => void openTest(linkAssignment.testLink!)}>Open test</button></div></article><article className="supplier-link-card live"><div><span className="status-pill status-LIVE">Live</span><h3>Live supplier template</h3><p>Use for real supplier traffic. The supplier must replace the respondent placeholder with a unique value.</p></div><code>{linkAssignment.liveLink ?? "Live link unavailable"}</code><div className="modal-actions"><button className="button small primary" disabled={!linkAssignment.liveLink} type="button" onClick={() => void copyLiveTemplate(linkAssignment.liveLink!)}>{copied === "live" ? "Copied" : "Copy live"}</button></div></article><article className="supplier-link-card short"><div><span className="status-pill status-ACTIVE">Short</span><h3>Short link (Cint/Toluna style)</h3><p>Clean entry URL without the long token. Same routing, same alias support — suppliers can use this instead of the long live link.</p></div><code>{linkAssignment.shortLink ?? "Short link unavailable"}</code><div className="modal-actions"><button className="button small primary" disabled={!linkAssignment.shortLink} type="button" onClick={() => void copyShortLink(linkAssignment.shortLink!)}>{copied === "short" ? "Copied" : "Copy short"}</button></div></article></div></section></div> : null}
  </section>;
}

function Cell({ editing, label, value, onChange, type = "text" }: { editing: boolean; label: string; value: string | number; onChange: (value: string) => void; type?: string }) { return <td>{editing ? <input aria-label={label} className="control" type={type} min={type === "number" ? (label.includes("quota") ? 1 : 0) : undefined} step={label.includes("CPI") ? "0.01" : undefined} value={value} onChange={(event) => onChange(event.target.value)} /> : label.includes("CPI") ? `$${Number(value).toFixed(2)}` : value || "Not set"}</td>; }
