"use client";
import { useEffect, useMemo, useState } from "react";
import { apiRequest } from "../../src/lib/api";

type Operator = "EQ" | "NE" | "IN" | "NOT_IN" | "GTE" | "LTE" | "BETWEEN";
type Rule = { id?: string; variableKey: string; operator: Operator; values: string[]; required: boolean; active: boolean };
const operatorLabels: Record<Operator, string> = { EQ: "Equals", NE: "Does not equal", IN: "Any of", NOT_IN: "None of", GTE: "At least", LTE: "At most", BETWEEN: "Between" };

export function ProjectEligibilityEditor({ projectId, configured, token, canOperate }: { projectId: string; configured: boolean; token?: string; canOperate: boolean }) {
  const [rules, setRules] = useState<Rule[]>([]); const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const headers = useMemo(() => token ? { authorization: `Bearer ${token}` } : undefined, [token]);
  useEffect(() => { if (configured && !token) return; void apiRequest<{ data: Rule[] }>(`/api/projects/${encodeURIComponent(projectId)}/eligibility`, { headers }).then((response) => { setRules(response.data); setMessage(""); }).catch(() => setMessage("Eligibility rules could not be loaded.")); }, [configured, headers, projectId, token]);
  function update(index: number, patch: Partial<Rule>) { setRules((current) => current.map((rule, position) => position === index ? { ...rule, ...patch } : rule)); }
  function add() { setRules((current) => [...current, { variableKey: `criteria_${current.length + 1}`, operator: "IN", values: ["value"], required: true, active: true }]); setEditing(true); }
  async function save() { setBusy(true); setMessage(""); try { const response = await apiRequest<{ data: Rule[] }>(`/api/projects/${encodeURIComponent(projectId)}/eligibility`, { method: "PUT", headers, body: JSON.stringify({ rules }) }); setRules(response.data); setEditing(false); setMessage("Eligibility rules saved. Test and live routing now enforce active rules."); } catch (error) { setMessage(error instanceof Error ? error.message : "Eligibility rules could not be saved."); } finally { setBusy(false); } }
  return <section className="panel" style={{ marginTop: 16 }}><div className="panel-head"><div><h2 className="panel-title">Eligibility rules</h2><span className="panel-note">Supplier links pass matching URL variables; every active required rule must pass.</span></div>{canOperate ? <div className="head-actions"><button className="button small ghost" type="button" onClick={add}>Add rule</button><button className="button small ghost" type="button" onClick={() => setEditing((value) => !value)}>{editing ? "Cancel" : "Edit"}</button></div> : null}</div>{message ? <div className="form-error data-error" role="status">{message}</div> : null}<div className="table-wrap"><table className="data-table"><thead><tr><th>Variable</th><th>Condition</th><th>Accepted value(s)</th><th>Required</th><th>Status</th>{editing ? <th>Action</th> : null}</tr></thead><tbody>{rules.map((rule, index) => <tr key={rule.id ?? `${rule.variableKey}-${index}`}><td>{editing ? <input aria-label={`Eligibility variable ${index + 1}`} className="control" value={rule.variableKey} onChange={(event) => update(index, { variableKey: event.target.value.toLowerCase().replace(/[^a-z0-9_]/g, "") })} /> : <code>{rule.variableKey}</code>}</td><td>{editing ? <select aria-label={`Eligibility operator ${index + 1}`} className="control" value={rule.operator} onChange={(event) => update(index, { operator: event.target.value as Operator })}>{Object.entries(operatorLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select> : operatorLabels[rule.operator]}</td><td>{editing ? <input aria-label={`Eligibility values ${index + 1}`} className="control" value={rule.values.join(", ")} onChange={(event) => update(index, { values: event.target.value.split(",").map((value) => value.trim()).filter(Boolean) })} /> : rule.values.join(", ")}</td><td>{editing ? <input aria-label={`Eligibility required ${index + 1}`} type="checkbox" checked={rule.required} onChange={(event) => update(index, { required: event.target.checked })} /> : rule.required ? "Yes" : "No"}</td><td>{editing ? <input aria-label={`Eligibility active ${index + 1}`} type="checkbox" checked={rule.active} onChange={(event) => update(index, { active: event.target.checked })} /> : rule.active ? "Active" : "Inactive"}</td>{editing ? <td><button className="button small ghost" type="button" onClick={() => setRules((current) => current.filter((_, position) => position !== index))}>Remove</button></td> : null}</tr>)}{rules.length === 0 ? <tr><td colSpan={editing ? 6 : 5} style={{ textAlign: "center", padding: 28 }}>No eligibility restrictions. Every valid supplier respondent may enter.</td></tr> : null}</tbody></table></div>{editing ? <div className="table-footer"><span>Use comma-separated values for Any of/None of; two numbers for Between.</span><button className="button primary small" disabled={busy} type="button" onClick={() => void save()}>{busy ? "Saving…" : "Save rules"}</button></div> : null}</section>;
}
