"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useAuth } from "../../src/features/auth/AuthProvider";
import { apiRequest } from "../../src/lib/api";
import { countryOptions, languageOptionsForCountry } from "../../src/lib/market-options";
import { automaticSurveyParameters, previewSurveyUrl } from "../../worker/domain/survey-url";
import Link from "./NavigationLink";

type Client = { name: string; status: string; salesUser?: string; respondentParameter?: string };
type Supplier = { name: string; status: string };
type Market = { countryCode: string; languageCode: string; targetQuota: string; expectedLoiMinutes: string; expectedIr: string };
const types = ["B2C", "B2B", "Healthcare", "Recontact", "Tracker", "Qualitative", "Quantitative", "Mixed method", "IHUT", "CLT"];
const categories = ["None", "Business & Professionals", "General Household", "Financial Technology", "Consumer Goods", "Healthcare", "Automotive", "Other"];
const today = new Date().toISOString().slice(0, 10);
const newMarket = (): Market => ({ countryCode: "", languageCode: "en", targetQuota: "", expectedLoiMinutes: "", expectedIr: "" });

export function ReferenceProjectCreationForm() {
  const { configured, session } = useAuth();
  const [clients, setClients] = useState<Client[]>(configured ? [] : [{ name: "Northstar Bank", status: "ACTIVE", salesUser: "Workspace sales", respondentParameter: "rid" }]);
  const [suppliers, setSuppliers] = useState<Supplier[]>(configured ? [] : [{ name: "CPX Research", status: "ACTIVE" }]);
  const [selectedClient, setSelectedClient] = useState(""); const [surveyUrl, setSurveyUrl] = useState("");
  const [markets, setMarkets] = useState<Market[]>([newMarket()]); const [supplierRows, setSupplierRows] = useState([{ name: "", cpi: "" }]);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [created, setCreated] = useState("");
  const headers = useMemo(() => session?.access_token ? { authorization: `Bearer ${session.access_token}` } : undefined, [session?.access_token]);
  useEffect(() => { if (configured && !session?.access_token) return; void Promise.all([apiRequest<{ data: Client[] }>("/api/clients", { headers }), apiRequest<{ data: Supplier[] }>("/api/suppliers", { headers })]).then(([clientResult, supplierResult]) => { setClients(clientResult.data.filter((item) => item.status === "ACTIVE")); setSuppliers(supplierResult.data.filter((item) => item.status === "ACTIVE")); }).catch(() => setError("Client and supplier lists could not be loaded.")); }, [configured, headers, session?.access_token]);
  const client = clients.find((item) => item.name === selectedClient); const parameters = automaticSurveyParameters(surveyUrl, client?.respondentParameter); const implementationUrl = surveyUrl ? previewSurveyUrl(surveyUrl, parameters) : "";
  function updateMarket(index: number, patch: Partial<Market>) { setMarkets((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item)); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(""); try { const response = await apiRequest<{ data: { id: string } }>("/api/projects", { method: "POST", headers, body: JSON.stringify({ projectName: form.get("projectName"), type: form.get("type"), category: form.get("category"), surveyMultiLink: form.get("surveyMultiLink") === "ON", client: selectedClient, clientPo: form.get("clientPo"), clientCpi: form.get("clientCpi"), segment: form.get("segment"), endDate: form.get("endDate"), markets: markets.map((item) => ({ ...item, targetQuota: item.targetQuota || form.get("quota") })), surveyUrl, testSurveyUrl: "", addAutomaticParameters: true, supplierAssignments: supplierRows.filter((item) => item.name).map((item) => ({ name: item.name, supplierCpi: item.cpi || 0 })), prescreeningQuestions: [], securityControls: {}, campaignBanner: "HIDE", geoSecurityEnabled: false }) }); setCreated(response.data.id); } catch (reason) { setError(reason instanceof Error ? reason.message : "Project could not be created."); } finally { setBusy(false); } }
  return <section className="panel survey-reference-form"><div className="survey-reference-title">Create Project</div>{error ? <div className="form-error" role="alert">{error}</div> : null}{created ? <div className="success-banner"><span>Project {created} created.</span><Link href={`/projects/${created}`}>Open project →</Link></div> : null}<form onSubmit={submit}>
    <div className="survey-reference-grid top-row"><Field label="Survey Name" name="projectName" required /><Select label="Project Type" name="type" options={types} required /><Select label="Survey Multi Link" name="surveyMultiLink" options={["OFF", "ON"]} /><Select label="Survey Category" name="category" options={categories} /></div>
    <div className="survey-reference-grid manager-row"><Field label="Project Manager" name="projectManager" value="Current operator" readOnly /><Field label="Secondary Proj. Manager" name="secondaryManager" placeholder="Select Secondary Proj. Manager" /><Field label="Create Date" name="createDate" type="date" value={today} readOnly /><Field label="End Date" name="endDate" type="date" /></div>
    <SectionTitle>AI Pre-Screening Questions:</SectionTitle><div className="survey-reference-grid three-row"><Select label="Pre-Screening" name="prescreening" options={["Off", "On"]} /><Select label="AI Pre-Screening Status" name="aiPrescreening" options={["Off", "On"]} /><Select label="Number Of Questions" name="questionCount" options={["5", "4", "3", "2", "1"]} /></div>
    <SectionTitle>Client Information:</SectionTitle><div className="survey-reference-grid client-row"><div className="field"><label htmlFor="reference-client">Client</label><select className="control" id="reference-client" required value={selectedClient} onChange={(event) => setSelectedClient(event.target.value)}><option value="">Select Client</option>{clients.map((item) => <option key={item.name}>{item.name}</option>)}</select></div><Field label="Sales Person" name="salesPerson" value={client?.salesUser ?? ""} placeholder="Select Sales Person" /><Field label="Client PO#" name="clientPo" /><Field label="Variable" name="variable" value={parameters[0]?.name ?? client?.respondentParameter ?? ""} readOnly /><Field label="Quota" name="quota" type="number" required /></div>
    {markets.map((item, index) => <div className="survey-reference-grid market-row" key={index}><div className="field"><label htmlFor={`country-${index}`}>Country</label><select className="control" id={`country-${index}`} required value={item.countryCode} onChange={(event) => { const countryCode = event.target.value; updateMarket(index, { countryCode, languageCode: languageOptionsForCountry(countryCode)[0]?.code ?? "en" }); }}><option value="">Select Country</option>{countryOptions.map((country) => <option key={country.code} value={country.code}>{country.name}</option>)}</select></div><Field label="IR" name={`ir-${index}`} type="number" value={item.expectedIr} onChange={(value) => updateMarket(index, { expectedIr: value })} required /><Field label="LOI" name={`loi-${index}`} type="number" value={item.expectedLoiMinutes} onChange={(value) => updateMarket(index, { expectedLoiMinutes: value })} required /><Field label="CPI" name="clientCpi" type="number" required={index === 0} /><Field label="Segment" name="segment" /><div className="field"><label htmlFor={`survey-link-${index}`}>Survey Link</label><input className="control" id={`survey-link-${index}`} type="url" value={surveyUrl} onChange={(event) => setSurveyUrl(event.target.value)} placeholder="https://survey.example/start?vid=XXXX" />{implementationUrl ? <small>Detected: {parameters[0]?.name} · {implementationUrl}</small> : null}</div><input type="hidden" value={item.targetQuota} readOnly /></div>)}
    <button className="button small reference-add" type="button" onClick={() => setMarkets((current) => [...current, newMarket()])}>Add More Field</button>
    <SectionTitle>ADD Supplier :</SectionTitle>{supplierRows.map((row, index) => <div className="survey-reference-grid supplier-row" key={index}><div className="field"><label>Name</label><select className="control" value={row.name} onChange={(event) => setSupplierRows((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, name: event.target.value } : item))}><option value="">Select Supplier</option>{suppliers.map((item) => <option key={item.name}>{item.name}</option>)}</select></div><Field label="Supplier CPI ($)" name={`supplier-cpi-${index}`} type="number" value={row.cpi} onChange={(value) => setSupplierRows((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, cpi: value } : item))} /></div>)}
    <div className="survey-reference-actions"><button className="button primary" disabled={busy} type="submit">{busy ? "Creating…" : "Create Project"}</button></div>
  </form></section>;
}
function SectionTitle({ children }: { children: React.ReactNode }) { return <h3 className="survey-reference-section">{children}</h3>; }
function Select({ label, name, options, required = false }: { label: string; name: string; options: string[]; required?: boolean }) { return <div className="field"><label htmlFor={`reference-${name}`}>{label}</label><select className="control" id={`reference-${name}`} name={name} required={required}><option value="">-select option-</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></div>; }
function Field({ label, name, type = "text", value, placeholder, required = false, readOnly = false, onChange }: { label: string; name: string; type?: string; value?: string; placeholder?: string; required?: boolean; readOnly?: boolean; onChange?: (value: string) => void }) { return <div className="field"><label htmlFor={`reference-${name}`}>{label}</label><input className="control" id={`reference-${name}`} name={name} type={type} value={onChange || readOnly ? value ?? "" : undefined} defaultValue={!onChange && !readOnly ? value : undefined} placeholder={placeholder} required={required} readOnly={readOnly} step={type === "number" ? "any" : undefined} onChange={onChange ? (event) => onChange(event.target.value) : undefined} /></div>; }
