"use client";

import { useEffect, useState } from "react";
import { useAuth } from "../../src/features/auth/AuthProvider";
import { apiRequest } from "../../src/lib/api";

type Session = {
  id: string; respondentRef: string; status: string; isTest?: boolean; startedAt: string; reachedClientAt?: string; completedAt?: string; durationSeconds?: number | null;
  projectCode?: string; projectName?: string; clientName?: string; countryCode?: string; languageCode?: string; supplierName?: string; supplierProjectId?: string; supplierCpi?: number;
  terminationReasonCode?: string; deviceType?: string; riskStatus?: string; riskFlagCount?: number; internalApprovalStatus?: string; vendorApprovalStatus?: string;
  events: Array<{ id: string; eventType: string; occurredAt: string; providerTransactionId?: string }>;
};
type ProjectOption = { code: string; name: string };
function csvCell(value: unknown) { let text = String(value ?? ""); if (/^[=+\-@]/.test(text)) text = `'${text}`; return `"${text.replaceAll('"', '""')}"`; }
function duration(seconds?: number | null) { if (seconds === null || seconds === undefined) return "—"; return `${Math.floor(seconds / 60)}m ${seconds % 60}s`; }

export function RespondentExplorer() {
  const { configured, session } = useAuth(); const [query, setQuery] = useState(""); const [project, setProject] = useState(""); const [projects, setProjects] = useState<ProjectOption[]>([]); const [sessions, setSessions] = useState<Session[]>([]); const [selected, setSelected] = useState<Session | null>(null); const [canReview, setCanReview] = useState(!configured); const [error, setError] = useState(""); const token = session?.access_token;
  useEffect(() => { const requestedProject = new URLSearchParams(window.location.search).get("project"); const initial = window.setTimeout(() => { if (requestedProject) setProject(requestedProject); }, 0); return () => window.clearTimeout(initial); }, []);
  useEffect(() => { if (configured && !token) return; const timer = setTimeout(() => { const params = new URLSearchParams({ q: query }); if (project) params.set("project", project); void apiRequest<{ data: Session[]; meta: { projects?: ProjectOption[]; canReview?: boolean } }>(`/api/respondents?${params}`, { headers: token ? { authorization: `Bearer ${token}` } : undefined }).then((response) => { setSessions(response.data); setProjects(response.meta.projects ?? []); setCanReview(response.meta.canReview === true); setSelected((current) => response.data.find((item) => item.id === current?.id) ?? response.data[0] ?? null); setError(""); }).catch(() => setError("Respondent sessions could not be loaded.")); }, 250); return () => clearTimeout(timer); }, [configured, project, query, token]);

  async function review(reviewType: "INTERNAL" | "VENDOR", status: string) {
    if (!selected) return;
    try { await apiRequest(`/api/respondents/${selected.id}/review`, { method: "PATCH", headers: token ? { authorization: `Bearer ${token}` } : undefined, body: JSON.stringify({ reviewType, status }) }); const change = reviewType === "INTERNAL" ? { internalApprovalStatus: status } : { vendorApprovalStatus: status }; setSessions((current) => current.map((item) => item.id === selected.id ? { ...item, ...change } : item)); setSelected((current) => current ? { ...current, ...change } : current); setError(""); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Respondent review could not be saved."); }
  }

  async function exportCsv() {
    try { const params = new URLSearchParams({ q: query, export: "1" }); if (project) params.set("project", project); const response = await apiRequest<{ data: Session[] }>(`/api/respondents?${params}`, { headers: token ? { authorization: `Bearer ${token}` } : undefined }); const rows = [["ResearchOps attempt ID", "Supplier attempt ID", "Project", "Project name", "Client", "Country", "Language", "Supplier", "Supplier project ID", "Supplier CPI", "Traffic", "Started", "Reached client", "Completed", "Duration seconds", "Final status", "Termination reason", "Device type", "Risk", "Risk flag count", "Internal approval", "Vendor approval"], ...response.data.map((item) => [item.id, item.respondentRef, item.projectCode, item.projectName, item.clientName, item.countryCode, item.languageCode, item.supplierName, item.supplierProjectId, item.supplierCpi, item.isTest ? "TEST" : "LIVE", item.startedAt, item.reachedClientAt, item.completedAt, item.durationSeconds, item.status, item.terminationReasonCode, item.deviceType, item.riskStatus, item.riskFlagCount, item.internalApprovalStatus, item.vendorApprovalStatus])]; const blob = new Blob(["\uFEFF", rows.map((row) => row.map(csvCell).join(",")).join("\r\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `respondents-${project || "all-projects"}.csv`; anchor.click(); URL.revokeObjectURL(url); }
    catch { setError("Respondent export could not be generated."); }
  }

  return <><div className="page-head"><div><div className="eyebrow">Event ledger</div><h1 className="page-title">Respondents</h1><p className="page-subtitle">Filter a project, export delivery records, and trace every session to its disposition.</p></div><div className="head-actions"><button className="button" type="button" disabled={!sessions.length} onClick={() => void exportCsv()}>Export CSV</button></div></div>
    <section className="panel"><div className="panel-head"><h2 className="panel-title">Session explorer</h2><div className="head-actions"><select aria-label="Filter respondents by project" className="control" value={project} onChange={(event) => setProject(event.target.value)}><option value="">All projects</option>{projects.map((item) => <option key={item.code} value={item.code}>{item.code} · {item.name}</option>)}</select><input aria-label="Search respondent reference" className="control search-control" placeholder="Respondent reference" value={query} onChange={(event) => setQuery(event.target.value)} /></div></div>{error ? <div className="form-error data-error" role="alert">{error}</div> : null}<div className="table-wrap"><table className="data-table"><thead><tr><th>Respondent</th><th>Project</th><th>Supplier</th><th>Traffic</th><th>Risk</th><th>Started</th><th>Duration</th><th>Status</th></tr></thead><tbody>{sessions.map((item) => <tr key={item.id}><td><button className="button small ghost" type="button" aria-label={`View timeline for ${item.respondentRef}`} onClick={() => setSelected(item)}>{item.respondentRef}</button></td><td>{item.projectCode} · {item.projectName}</td><td>{item.supplierName ?? "Direct"}</td><td>{item.isTest ? "TEST" : "LIVE"}</td><td>{item.riskStatus ?? "CLEAR"}{item.riskFlagCount ? ` (${item.riskFlagCount})` : ""}</td><td>{new Date(item.startedAt).toLocaleString()}</td><td>{duration(item.durationSeconds)}</td><td><span className={`status-pill status-${item.status}`}>{item.status}</span></td></tr>)}{sessions.length === 0 ? <tr><td colSpan={8} style={{ padding: 28, textAlign: "center" }}>No matching sessions.</td></tr> : null}</tbody></table></div></section>
    {selected ? <section className="panel" style={{ marginTop: 16 }}><div className="panel-head"><div><h2 className="panel-title">{selected.respondentRef}</h2><span className="panel-note">{selected.countryCode || "No market"} · {selected.deviceType ?? "UNKNOWN"} · {selected.terminationReasonCode ?? "No termination reason"}</span></div>{canReview ? <div className="head-actions"><button className="button small ghost" type="button" onClick={() => void review("INTERNAL", "APPROVED")}>Approve internally</button><button className="button small ghost" type="button" onClick={() => void review("INTERNAL", "REJECTED")}>Reject internally</button><button className="button small ghost" type="button" onClick={() => void review("VENDOR", "APPROVED")}>Vendor approved</button><button className="button small ghost" type="button" onClick={() => void review("VENDOR", "DISPUTED")}>Vendor disputed</button></div> : null}</div><div className="info-list"><div className="info-row"><span>ResearchOps attempt ID</span><strong>{selected.id}</strong></div><div className="info-row"><span>Supplier attempt ID</span><strong>{selected.respondentRef}</strong></div><div className="info-row"><span>Internal review</span><strong>{selected.internalApprovalStatus ?? "NOT_REVIEWED"}</strong></div><div className="info-row"><span>Vendor reconciliation</span><strong>{selected.vendorApprovalStatus ?? "NOT_REVIEWED"}</strong></div>{[...selected.events].sort((a, b) => a.occurredAt.localeCompare(b.occurredAt)).map((event) => <div className="info-row" key={event.id}><span>{new Date(event.occurredAt).toLocaleString()}</span><strong>{event.eventType}{event.providerTransactionId ? ` · ${event.providerTransactionId}` : ""}</strong></div>)}</div></section> : null}</>;
}
