"use client";
import { useEffect, useState } from "react";
import { useAuth } from "../../src/features/auth/AuthProvider";
import { apiRequest } from "../../src/lib/api";

type Session = { id: string; respondentRef: string; status: string; startedAt: string; completedAt?: string; durationSeconds?: number | null; projectCode?: string; projectName?: string; supplierName?: string; supplierCpi?: number; events: Array<{ id: string; eventType: string; occurredAt: string; providerTransactionId?: string }> };
type ProjectOption = { code: string; name: string };
function csvCell(value: unknown) { let text = String(value ?? ""); if (/^[=+\-@]/.test(text)) text = `'${text}`; return `"${text.replaceAll('"', '""')}"`; }
function duration(seconds?: number | null) { if (seconds === null || seconds === undefined) return "—"; return `${Math.floor(seconds / 60)}m ${seconds % 60}s`; }

export function RespondentExplorer() {
  const { configured, session } = useAuth(); const [query, setQuery] = useState(""); const [project, setProject] = useState(""); const [projects, setProjects] = useState<ProjectOption[]>([]); const [sessions, setSessions] = useState<Session[]>([]); const [selected, setSelected] = useState<Session | null>(null); const [error, setError] = useState(""); const token = session?.access_token;
  useEffect(() => {
    const requestedProject = new URLSearchParams(window.location.search).get("project");
    const initial = window.setTimeout(() => { if (requestedProject) setProject(requestedProject); }, 0);
    return () => window.clearTimeout(initial);
  }, []);
  useEffect(() => { if (configured && !token) return; const timer = setTimeout(() => { const params = new URLSearchParams({ q: query }); if (project) params.set("project", project); void apiRequest<{ data: Session[]; meta: { projects?: ProjectOption[] } }>(`/api/respondents?${params}`, { headers: token ? { authorization: `Bearer ${token}` } : undefined }).then((response) => { setSessions(response.data); setProjects(response.meta.projects ?? []); setSelected((current) => response.data.find((item) => item.id === current?.id) ?? response.data[0] ?? null); setError(""); }).catch(() => setError("Respondent sessions could not be loaded.")); }, 250); return () => clearTimeout(timer); }, [configured, project, query, token]);
  async function exportCsv() { try { const params = new URLSearchParams({ q: query, export: "1" }); if (project) params.set("project", project); const response = await apiRequest<{ data: Session[] }>(`/api/respondents?${params}`, { headers: token ? { authorization: `Bearer ${token}` } : undefined }); const rows = [["Respondent", "Project", "Project name", "Supplier", "Supplier CPI", "Started", "Completed", "Duration seconds", "Status"], ...response.data.map((item) => [item.respondentRef, item.projectCode, item.projectName, item.supplierName, item.supplierCpi, item.startedAt, item.completedAt, item.durationSeconds, item.status])]; const blob = new Blob(["\uFEFF", rows.map((row) => row.map(csvCell).join(",")).join("\r\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `respondents-${project || "all-projects"}.csv`; anchor.click(); URL.revokeObjectURL(url); } catch { setError("Respondent export could not be generated."); } }
  return <><div className="page-head"><div><div className="eyebrow">Event ledger</div><h1 className="page-title">Respondents</h1><p className="page-subtitle">Filter a project, export delivery records, and trace every session to its disposition.</p></div><div className="head-actions"><button className="button" type="button" disabled={!sessions.length} onClick={() => void exportCsv()}>Export CSV</button></div></div><section className="panel"><div className="panel-head"><h2 className="panel-title">Session explorer</h2><div className="head-actions"><select aria-label="Filter respondents by project" className="control" value={project} onChange={(event) => setProject(event.target.value)}><option value="">All projects</option>{projects.map((item) => <option key={item.code} value={item.code}>{item.code} · {item.name}</option>)}</select><input aria-label="Search respondent reference" className="control search-control" placeholder="Respondent reference" value={query} onChange={(event) => setQuery(event.target.value)} /></div></div>{error ? <div className="form-error data-error" role="alert">{error}</div> : null}<div className="table-wrap"><table className="data-table"><thead><tr><th>Respondent</th><th>Project</th><th>Supplier</th><th>Supplier CPI</th><th>Started</th><th>Duration</th><th>Status</th></tr></thead><tbody>{sessions.map((item) => <tr key={item.id}><td><button className="button small ghost" type="button" aria-label={`View timeline for ${item.respondentRef}`} onClick={() => setSelected(item)}>{item.respondentRef}</button></td><td>{item.projectCode} · {item.projectName}</td><td>{item.supplierName ?? "Direct"}</td><td>${Number(item.supplierCpi ?? 0).toFixed(2)}</td><td>{new Date(item.startedAt).toLocaleString()}</td><td>{duration(item.durationSeconds)}</td><td><span className={`status-pill status-${item.status}`}>{item.status}</span></td></tr>)}{sessions.length === 0 ? <tr><td colSpan={7} style={{ padding: 28, textAlign: "center" }}>No matching sessions.</td></tr> : null}</tbody></table></div></section>{selected ? <section className="panel" style={{ marginTop: 16 }}><div className="panel-head"><div><h2 className="panel-title">{selected.respondentRef}</h2><span className="panel-note">Immutable event timeline · {duration(selected.durationSeconds)}</span></div></div><div className="info-list">{[...selected.events].sort((a, b) => a.occurredAt.localeCompare(b.occurredAt)).map((event) => <div className="info-row" key={event.id}><span>{new Date(event.occurredAt).toLocaleString()}</span><strong>{event.eventType}{event.providerTransactionId ? ` · ${event.providerTransactionId}` : ""}</strong></div>)}</div></section> : null}</>;
}
