import assert from"node:assert/strict";import test from"node:test";
const url=process.env.TEST_SUPABASE_URL,key=process.env.TEST_SUPABASE_ANON_KEY,service=process.env.TEST_SUPABASE_SERVICE_ROLE_KEY;
const enabled=Boolean(url&&key&&service);const password="LocalTest!2026";const run=`${Date.now()}-${Math.random().toString(16).slice(2)}`;
async function call(path,{token=key,apikey=key,method="GET",body,headers={}}={}){const response=await fetch(`${url}${path}`,{method,headers:{apikey,authorization:`Bearer ${token}`,"content-type":"application/json",...headers},body:body===undefined?undefined:JSON.stringify(body)});const text=await response.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}return{response,data}}
async function signup(label){const result=await call("/auth/v1/signup",{method:"POST",body:{email:`${label}-${run}@example.test`,password}});assert.equal(result.response.status,200);assert.ok(result.data.access_token);return result.data}
test("local Supabase proves tenant isolation, roles, project persistence, and event idempotency",{skip:!enabled},async()=>{
 const [ownerA,ownerB,analyst]=await Promise.all([signup("owner-a"),signup("owner-b"),signup("analyst")]);
 const orgAResult=await call("/rest/v1/rpc/create_initial_organization",{token:ownerA.access_token,method:"POST",body:{p_name:`Workspace A ${run}`}});assert.equal(orgAResult.response.status,200);const orgA=orgAResult.data[0].organization_id;
 const orgBResult=await call("/rest/v1/rpc/create_initial_organization",{token:ownerB.access_token,method:"POST",body:{p_name:`Workspace B ${run}`}});assert.equal(orgBResult.response.status,200);const orgB=orgBResult.data[0].organization_id;assert.notEqual(orgA,orgB);
 const client=await call("/rest/v1/clients?select=*",{token:ownerA.access_token,method:"POST",headers:{Prefer:"return=representation"},body:{organization_id:orgA,name:`Tenant A Client ${run}`,code:`A${Date.now()}`}});assert.equal(client.response.status,201,JSON.stringify(client.data));
 const hidden=await call(`/rest/v1/clients?organization_id=eq.${orgA}&select=id`,{token:ownerB.access_token});assert.equal(hidden.response.status,200);assert.deepEqual(hidden.data,[]);
 const denied=await call("/rest/v1/clients",{token:ownerB.access_token,method:"POST",body:{organization_id:orgA,name:"Cross tenant",code:`X${Date.now()}`}});assert.equal(denied.response.status,403);
 const membership=await call("/rest/v1/organization_members",{token:service,apikey:service,method:"POST",body:{organization_id:orgA,user_id:analyst.user.id,role:"ANALYST"}});assert.equal(membership.response.status,201);
 const readable=await call("/rest/v1/projects?select=id",{token:analyst.access_token});assert.equal(readable.response.status,200);
 const analystWrite=await call("/rest/v1/projects",{token:analyst.access_token,method:"POST",body:{organization_id:orgA,project_code:`PRJ-A${Date.now()}`,project_name:"Denied"}});assert.equal(analystWrite.response.status,403);
 const project=await call("/rest/v1/rpc/create_project_with_market",{token:ownerA.access_token,method:"POST",body:{p_project_name:"Integration Project",p_client_name:`Tenant A Client ${run}`,p_client_po:"TEST-1",p_project_type:"Consumer",p_category:"Test",p_client_cpi:10,p_quota:100,p_country_code:"US",p_language_code:"en",p_expected_loi_minutes:10,p_expected_ir:40,p_start_date:"2026-08-19",p_supplier_names:["CPX Research"]}});assert.equal(project.response.status,200,JSON.stringify(project.data));const code=project.data[0].project_code;
 const supplierRows=await call(`/rest/v1/suppliers?organization_id=eq.${orgA}&code=eq.CPX&select=id`,{token:service,apikey:service});const supplierId=supplierRows.data[0].id;
 const eventBody={p_organization_id:orgA,p_project_code:code,p_supplier_id:supplierId,p_respondent_ref:`RESP-${run}`,p_event_type:"START",p_provider_transaction_id:`TX-${run}`,p_occurred_at:new Date().toISOString(),p_metadata:{}};
 const first=await call("/rest/v1/rpc/ingest_survey_event",{token:service,apikey:service,method:"POST",body:eventBody});assert.equal(first.response.status,200);assert.equal(first.data[0].created,true);
 const replay=await call("/rest/v1/rpc/ingest_survey_event",{token:service,apikey:service,method:"POST",body:eventBody});assert.equal(replay.response.status,200);assert.equal(replay.data[0].created,false);assert.equal(replay.data[0].event_id,first.data[0].event_id);
 const metrics=await call(`/rest/v1/project_event_metrics?project_code=eq.${code}&select=starts`,{token:ownerA.access_token});assert.equal(metrics.response.status,200);assert.equal(metrics.data[0].starts,1);
});
