export type ProjectStatus = "PENDING" | "LIVE" | "PAUSED" | "ID_SUBMITTED" | "INVOICED" | "CLOSED";

export interface Project {
  id: string;
  name: string;
  client: string;
  clientCode?: string;
  clientPo: string;
  market: string;
  marketCountryCode?: string;
  type: string;
  manager: string;
  secondaryManager?: string;
  salesPerson?: string;
  secondaryManagerId?: string;
  salesPersonId?: string;
  status: ProjectStatus;
  starts: number;
  reached: number;
  l24: number;
  completes: number;
  terminates: number;
  overQuota: number;
  qualityTerm: number;
  abandons?: number;
  inProgress?: number;
  abandonRate: number;
  incidenceRate: number;
  conversionRate: number;
  testStarts?: number;
  testCompletes?: number;
  testTerminates?: number;
  testOverQuota?: number;
  testQualityTerm?: number;
  cpi: number;
  quota?: number;
  category?: string;
  createdAt?: string;
  updatedAt?: string;
  startDate?: string;
  endDate?: string;
  surveyUrl?: string;
  testSurveyUrl?: string;
  surveyParameters?: Array<{ name: string; value: string }>;
  markets?: Array<{ countryCode: string; languageCode: string; targetQuota: number; expectedLoiMinutes: number; expectedIr: number }>;
  supplierAssignments?: Array<{ supplierName: string; supplierProjectId: string; supplierCpi: number; targetQuota: number; status: string }>;
  eligibilityRules?: Array<{ variableKey: string; operator: string; values: string[]; required: boolean; active: boolean }>;
  quotaCells?: Array<{ name: string; targetQuota: number; priority: number; active: boolean; conditions: unknown }>;
  securityTerminateUrl?: string;
  averageDurationSeconds?: number;
  lastComplete: string;
  lastEventAt?: string;
}
