import { authorizationError, authorizeWorkspace, workspacePermissions } from "../lib/authorization";
import { isSupabaseConfigured, supabaseJson, type SupabaseEnv } from "../lib/supabase";
const demo = [{ id: "00000000-0000-4000-8000-000000000099", ruleCode: "SPEEDING", severity: "MEDIUM", status: "OPEN", createdAt: "2026-08-18T08:27:00Z", evidence: { durationSeconds: 42, minimumSeconds: 60 }, session: { respondentRef: "RESP-78291", project: { projectCode: "PRJ-1048", projectName: "Digital Wallet Adoption" } } }];
function map(row: Record<string, unknown>) { const session = row.survey_sessions as { respondent_ref?: string; projects?: { project_code?: string; project_name?: string } } | undefined; return { id: row.id, ruleCode: row.rule_code, severity: row.severity, status: row.status, createdAt: row.created_at, evidence: row.evidence, session: { respondentRef: session?.respondent_ref, project: { projectCode: session?.projects?.project_code, projectName: session?.projects?.project_name } } }; }
export async function handleFraudApi(request: Request, pathname: string, env: SupabaseEnv): Promise<Response | null> {
  const match = pathname.match(/^\/api\/fraud-flags(?:\/([0-9a-f-]{36}))?$/i); if (!match) return null;
  if (!isSupabaseConfigured(env)) { if (request.method === "GET" && !match[1]) return Response.json({ data: demo, meta: { source: "mock", canOperate: true } }); if (request.method === "PATCH" && match[1]) { const body = await request.json().catch(() => null) as { status?: string } | null; return ["CONFIRMED", "DISMISSED"].includes(body?.status ?? "") ? Response.json({ data: { id: match[1], status: body?.status } }) : Response.json({ error: "Valid resolution required" }, { status: 400 }); } return null; }
  const access = await authorizeWorkspace(request, env, request.method === "GET" ? workspacePermissions.read : workspacePermissions.operate); if (!access.ok) return authorizationError(access);
  try {
    if (request.method === "GET" && !match[1]) { const rows = await supabaseJson<Record<string, unknown>[]>(env, "/rest/v1/fraud_flags?select=id,rule_code,severity,status,evidence,created_at,survey_sessions(respondent_ref,projects(project_code,project_name))&order=created_at.desc&limit=100", access.authorization); const canOperate = access.membership.role === "OWNER" || access.membership.role === "ADMIN" || access.membership.role === "PM"; return Response.json({ data: rows.map(map), meta: { source: "supabase", canOperate } }); }
    if (request.method === "PATCH" && match[1]) { const body = await request.json().catch(() => null) as { status?: string } | null; if (!["CONFIRMED", "DISMISSED"].includes(body?.status ?? "")) return Response.json({ error: "Valid resolution required" }, { status: 400 }); const rows = await supabaseJson(env, "/rest/v1/rpc/resolve_fraud_flag", access.authorization, { method: "POST", body: JSON.stringify({ p_flag_id: match[1], p_status: body?.status }) }); return Response.json({ data: Array.isArray(rows) ? rows[0] : rows, meta: { source: "supabase" } }); }
  } catch { return Response.json({ error: "Fraud review request failed" }, { status: 502 }); }
  return null;
}
