import { authorizationError, authorizeWorkspace, workspacePermissions } from "../lib/authorization.ts";
import { isSupabaseConfigured, supabaseJson, type SupabaseEnv } from "../lib/supabase.ts";

const demo = [{ id: "session-demo-1", respondentRef: "RESP-78291", status: "COMPLETE", isTest: false, startedAt: "2026-08-18T08:15:00Z", completedAt: "2026-08-18T08:27:00Z", durationSeconds: 720, projectCode: "PRJ-1048", projectName: "Digital Wallet Adoption", supplierName: "CPX Research", supplierCpi: 7.5, events: [{ id: "event-1", eventType: "START", occurredAt: "2026-08-18T08:15:00Z" }, { id: "event-2", eventType: "REACHED_CLIENT", occurredAt: "2026-08-18T08:16:00Z" }, { id: "event-3", eventType: "COMPLETE", occurredAt: "2026-08-18T08:27:00Z" }] }];
function clean(value: string | null) { return (value ?? "").replace(/[%*,()]/g, " ").trim().slice(0, 100); }
function first<T>(value: T | T[] | null | undefined) { return Array.isArray(value) ? value[0] : value; }

export async function handleRespondentsApi(request: Request, pathname: string, env: SupabaseEnv): Promise<Response | null> {
  const reviewMatch = pathname.match(/^\/api\/respondents\/([A-Za-z0-9-]{1,80})\/review$/i);
  if (reviewMatch && request.method === "PATCH") {
    if (!isSupabaseConfigured(env)) return Response.json({ data: { id: reviewMatch[1] }, meta: { source: "mock" } });
    if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(reviewMatch[1])) return Response.json({ error: "A valid respondent session is required" }, { status: 400 });
    const access = await authorizeWorkspace(request, env, workspacePermissions.review); if (!access.ok) return authorizationError(access);
    const body = await request.json().catch(() => null) as Record<string, unknown> | null; const reviewType = String(body?.reviewType ?? "").toUpperCase(); const status = String(body?.status ?? "").toUpperCase(); const note = String(body?.note ?? "").trim();
    const valid = (reviewType === "INTERNAL" && ["PENDING", "APPROVED", "REJECTED"].includes(status)) || (reviewType === "VENDOR" && ["PENDING", "APPROVED", "DISPUTED", "REJECTED"].includes(status));
    if (!valid || note.length > 500) return Response.json({ error: "A valid review type, status, and note are required" }, { status: 400 });
    try { const rows = await supabaseJson<Record<string, unknown>[]>(env, "/rest/v1/rpc/review_survey_session", access.authorization, { method: "POST", body: JSON.stringify({ p_session_id: reviewMatch[1], p_review_type: reviewType, p_status: status, p_note: note || null }) }); return Response.json({ data: rows[0] ?? { id: reviewMatch[1] }, meta: { source: "supabase" } }); }
    catch { return Response.json({ error: "Respondent review could not be saved" }, { status: 502 }); }
  }
  if (pathname !== "/api/respondents" || request.method !== "GET") return null;
  const search = new URL(request.url).searchParams; const q = clean(search.get("q")); const projectCode = clean(search.get("project")).toUpperCase(); const projectCodes = (search.get("projects") ?? "").split(",").map((code) => clean(code).toUpperCase()).filter((code) => /^[A-Z]{2,10}-[A-Z0-9-]+$/.test(code)).slice(0, 100); const limit = search.get("export") === "1" ? 5000 : 100;
  if (!isSupabaseConfigured(env)) { const filtered = demo.filter((item) => (!q || item.respondentRef.toLowerCase().includes(q.toLowerCase())) && (!projectCode || item.projectCode === projectCode)); return Response.json({ data: filtered, meta: { source: "mock", canReview: true, truncated: false, projects: [{ code: "PRJ-1048", name: "Digital Wallet Adoption" }] } }); }
  const access = await authorizeWorkspace(request, env, workspacePermissions.read); if (!access.ok) return authorizationError(access);
  try {
    const restrictProjects = Boolean(projectCode || projectCodes.length); const projectRelation = restrictProjects ? "projects!inner(project_code,project_name,status,clients(name),project_markets(country_code,language_code,expected_loi_minutes))" : "projects(project_code,project_name,status,clients(name),project_markets(country_code,language_code,expected_loi_minutes))";
    const params = new URLSearchParams({ select: `id,respondent_ref,status,is_test,started_at,completed_at,country_code,language_code,device_type,termination_reason_code,termination_reason_source,internal_approval_status,vendor_approval_status,${projectRelation},project_suppliers(supplier_project_id,supplier_cpi,suppliers(name)),survey_events(id,event_type,occurred_at,provider_transaction_id),fraud_flags(rule_code,severity,status),survey_response_values(variable_key,value,source,captured_at)`, order: "started_at.desc", "survey_events.order": "occurred_at.asc,id.asc", limit: String(limit) });
    if (q) params.set("respondent_ref", `ilike.*${q}*`); if (projectCode) params.set("projects.project_code", `eq.${projectCode}`); else if (projectCodes.length) params.set("projects.project_code", `in.(${projectCodes.join(",")})`);
    const [rows, projectRows] = await Promise.all([
      supabaseJson<Record<string, unknown>[]>(env, `/rest/v1/survey_sessions?${params}`, access.authorization),
      supabaseJson<Array<{ project_code: string; project_name: string }>>(env, "/rest/v1/projects?select=project_code,project_name&order=created_at.desc&limit=1000", access.authorization),
    ]);
    const data = rows.map((row) => {
      const project = first(row.projects as { project_code?: string; project_name?: string; status?: string; clients?: { name?: string } | { name?: string }[]; project_markets?: Array<{ country_code?: string; language_code?: string; expected_loi_minutes?: number }> } | { project_code?: string; project_name?: string; status?: string; clients?: { name?: string } | { name?: string }[]; project_markets?: Array<{ country_code?: string; language_code?: string; expected_loi_minutes?: number }> }[] | null);
      const assignment = first(row.project_suppliers as { supplier_project_id?: string; supplier_cpi?: number | string; suppliers?: { name?: string } | { name?: string }[] } | { supplier_project_id?: string; supplier_cpi?: number | string; suppliers?: { name?: string } | { name?: string }[] }[] | null);
      const supplier = first(assignment?.suppliers); const events = Array.isArray(row.survey_events) ? row.survey_events as Record<string, unknown>[] : [];
      const flags = Array.isArray(row.fraud_flags) ? row.fraud_flags as Record<string, unknown>[] : []; const variables = Array.isArray(row.survey_response_values) ? row.survey_response_values as Record<string, unknown>[] : []; const market = project?.project_markets?.[0]; const client = first(project?.clients); const reached = events.find((event) => event.event_type === "REACHED_CLIENT"); const transaction = [...events].reverse().find((event) => event.provider_transaction_id);
      const started = new Date(String(row.started_at)).getTime(); const completed = row.completed_at ? new Date(String(row.completed_at)).getTime() : Number.NaN;
      const openFlags = flags.filter((flag) => flag.status === "OPEN"); const riskStatus = openFlags.some((flag) => flag.severity === "HIGH") ? "HIGH" : openFlags.some((flag) => flag.severity === "MEDIUM") ? "MEDIUM" : openFlags.length ? "LOW" : "CLEAR";
      return { id: row.id, respondentRef: row.respondent_ref, status: row.status, isTest: row.is_test === true, startedAt: row.started_at, reachedClientAt: reached?.occurred_at, completedAt: row.completed_at, durationSeconds: Number.isFinite(completed) ? Math.max(0, Math.round((completed - started) / 1000)) : null, projectCode: project?.project_code, projectName: project?.project_name, projectStatus: project?.status, clientName: client?.name, countryCode: row.country_code ?? market?.country_code, languageCode: row.language_code ?? market?.language_code, expectedLoiMinutes: market?.expected_loi_minutes, supplierName: supplier?.name, supplierProjectId: assignment?.supplier_project_id, supplierCpi: Number(assignment?.supplier_cpi ?? 0), providerTransactionId: transaction?.provider_transaction_id, terminationReasonCode: row.termination_reason_code, terminationReasonSource: row.termination_reason_source, deviceType: row.device_type ?? "UNKNOWN", riskStatus, riskFlagCount: flags.length, riskFlags: flags.map((flag) => ({ ruleCode: flag.rule_code, severity: flag.severity, status: flag.status })), internalApprovalStatus: row.internal_approval_status ?? "NOT_REVIEWED", vendorApprovalStatus: row.vendor_approval_status ?? "NOT_REVIEWED", variables: variables.map((value) => ({ key: value.variable_key, value: value.value, source: value.source, capturedAt: value.captured_at })), events: events.map((event) => ({ id: event.id, eventType: event.event_type, occurredAt: event.occurred_at, providerTransactionId: event.provider_transaction_id })) };
    });
    return Response.json({ data, meta: { source: "supabase", canReview: workspacePermissions.review.includes(access.membership.role as "OWNER" | "ADMIN" | "PM" | "ANALYST"), limit, truncated: data.length >= limit, projects: projectRows.map((item) => ({ code: item.project_code, name: item.project_name })) } }, { headers: { "cache-control": "private, no-store" } });
  } catch { return Response.json({ error: "Respondent sessions could not be loaded" }, { status: 502 }); }
}
